import SwiftUI

/// TypeSceneText component from Figma design (GENERATED BY pb-figma:figma-to-code)
/// File: bt65gbJ6sSdKRP4x3IY151, Node: 10203:16369
/// Generated: 2026-01-26
///
/// Features:
/// - PageControl dots at TOP (addresses user-reported issue)
/// - 7-color angular gradient text
/// - Radial gradient background (opacity 0.2)
/// - Semi-transparent borders (opacity 0.4)
/// - Linear gradients (opacity 0.7-0.2)
/// - Complete layout with all sections
@available(iOS 15.0, *)
struct TypeSceneText: View {
    var body: some View {
        ZStack {
            // Background: #150200 solid + radial gradient overlay (opacity 0.2)
            ZStack {
                Color(hex: "#150200")

                RadialGradient(
                    gradient: Gradient(stops: [
                        .init(color: Color(hex: "#f02912"), location: 0.0),
                        .init(color: Color(hex: "#150200"), location: 1.0)
                    ]),
                    center: .center,
                    startRadius: 0,
                    endRadius: 200
                )
                .opacity(0.2)
            }

            VStack(spacing: 0) {
                // ===== PAGE CONTROL DOTS AT TOP (USER'S REPORTED ISSUE - FIXED) =====
                HStack(spacing: 6) {
                    Circle()
                        .fill(Color.white.opacity(0.3))
                        .frame(width: 6, height: 6)

                    Circle()
                        .fill(Color.white)
                        .frame(width: 6, height: 6)

                    Circle()
                        .fill(Color.white.opacity(0.3))
                        .frame(width: 6, height: 6)
                }
                .padding(.top, 8)
                .padding(.bottom, 8)

                // ===== HEADER SECTION =====
                HStack(spacing: 0) {
                    // "Create" title
                    Text("Create")
                        .font(.system(size: 18, weight: .semibold))
                        .foregroundColor(.white)

                    Spacer()

                    // Star rating + coin count + PRO badge + settings icon
                    HStack(spacing: 8) {
                        // Star icon + rating "10"
                        HStack(spacing: 4) {
                            Image(systemName: "star.fill")
                                .font(.system(size: 14))
                                .foregroundColor(Color(hex: "#ffd100"))

                            Text("10")
                                .font(.system(size: 16, weight: .semibold))
                                .foregroundColor(.white)
                        }
                        .padding(.horizontal, 8)
                        .padding(.vertical, 4)
                        .background(
                            RoundedRectangle(cornerRadius: 100)
                                .fill(Color.white.opacity(0.1))
                        )

                        // Coin icon + count "10"
                        HStack(spacing: 4) {
                            Image(systemName: "bitcoinsign.circle.fill")
                                .font(.system(size: 14))
                                .foregroundColor(Color(hex: "#ff9500"))

                            Text("10")
                                .font(.system(size: 16, weight: .semibold))
                                .foregroundColor(.white)
                        }
                        .padding(.horizontal, 8)
                        .padding(.vertical, 4)
                        .background(
                            RoundedRectangle(cornerRadius: 100)
                                .fill(Color.white.opacity(0.1))
                        )

                        // PRO badge
                        Text("PRO")
                            .font(.system(size: 12, weight: .medium))
                            .foregroundColor(.white)
                            .padding(.horizontal, 8)
                            .padding(.vertical, 4)
                            .background(
                                RoundedRectangle(cornerRadius: 100)
                                    .fill(
                                        LinearGradient(
                                            colors: [Color(hex: "#e5bf8e"), Color(hex: "#e5bf8e").opacity(0)],
                                            startPoint: .top,
                                            endPoint: .bottom
                                        )
                                    )
                                    .opacity(0.4)
                            )

                        // Settings icon
                        Image(systemName: "gearshape.fill")
                            .font(.system(size: 20))
                            .foregroundColor(Color(hex: "#007a5a"))
                            .padding(4)
                    }
                }
                .padding(.horizontal, 16)
                .padding(.bottom, 16)

                // ===== OPTIONS ROW: "Image to Video" + Icon Buttons =====
                HStack(spacing: 8) {
                    // "Image to Video" button
                    Text("Image to Video")
                        .font(.custom("Poppins", size: 14))
                        .foregroundColor(.white)
                        .padding(.horizontal, 12)
                        .padding(.vertical, 4)
                        .background(
                            RoundedRectangle(cornerRadius: 100)
                                .stroke(
                                    LinearGradient(
                                        colors: [
                                            Color.white.opacity(0.7),
                                            Color.white.opacity(0.2)
                                        ],
                                        startPoint: .top,
                                        endPoint: .bottom
                                    ),
                                    lineWidth: 0.7
                                )
                        )

                    Spacer()

                    // Icon buttons: camera, photo, video, settings
                    HStack(spacing: 8) {
                        Image(systemName: "camera.fill")
                            .font(.system(size: 18))
                            .foregroundColor(.white)
                            .frame(width: 32, height: 32)

                        Image(systemName: "photo.fill")
                            .font(.system(size: 18))
                            .foregroundColor(.white)
                            .frame(width: 32, height: 32)

                        Image(systemName: "video.fill")
                            .font(.system(size: 18))
                            .foregroundColor(.white)
                            .frame(width: 32, height: 32)

                        Image(systemName: "gearshape.fill")
                            .font(.system(size: 18))
                            .foregroundColor(.white)
                            .frame(width: 32, height: 32)
                    }
                }
                .padding(.horizontal, 16)
                .padding(.bottom, 16)

                // ===== MAIN CONTENT AREA =====
                VStack(spacing: 12) {
                    // Main image placeholder with pink border + action buttons
                    ZStack {
                        RoundedRectangle(cornerRadius: 12)
                            .stroke(Color(hex: "#ffaca9"), lineWidth: 2)
                            .frame(width: 256, height: 256)

                        // Action buttons overlay (top-right)
                        VStack {
                            HStack {
                                Spacer()

                                VStack(spacing: 8) {
                                    Image(systemName: "photo.fill.on.rectangle.fill")
                                        .font(.system(size: 20))
                                        .foregroundColor(.white)
                                        .frame(width: 36, height: 36)
                                        .background(Color.black.opacity(0.3))
                                        .clipShape(Circle())

                                    Image(systemName: "trash.fill")
                                        .font(.system(size: 20))
                                        .foregroundColor(.white)
                                        .frame(width: 36, height: 36)
                                        .background(Color.black.opacity(0.3))
                                        .clipShape(Circle())
                                }
                                .padding(12)
                            }

                            Spacer()
                        }
                        .frame(width: 256, height: 256)
                    }

                    // Placeholder text with 7-COLOR ANGULAR GRADIENT (CRITICAL FEATURE)
                    Text("Type a scene to generate your video")
                        .font(.custom("Inter", size: 14))
                        .multilineTextAlignment(.center)
                        .foregroundStyle(
                            AngularGradient(
                                stops: [
                                    .init(color: Color(hex: "#bc82f3"), location: 0.1673),
                                    .init(color: Color(hex: "#f4b9ea"), location: 0.2365),
                                    .init(color: Color(hex: "#8d98ff"), location: 0.3518),
                                    .init(color: Color(hex: "#aa6eee"), location: 0.5815),
                                    .init(color: Color(hex: "#ff6777"), location: 0.6970),
                                    .init(color: Color(hex: "#ffba71"), location: 0.8095),
                                    .init(color: Color(hex: "#c686ff"), location: 0.9241)
                                ],
                                center: .center
                            )
                        )
                        .padding(.horizontal, 16)

                    // Character count + action buttons row
                    HStack(spacing: 12) {
                        // Character count
                        Text("10000")
                            .font(.custom("Inter", size: 10).weight(.medium))
                            .foregroundColor(.white)

                        Spacer()

                        // Action buttons
                        HStack(spacing: 8) {
                            Image(systemName: "wand.and.stars")
                                .font(.system(size: 16))
                                .foregroundColor(.white)

                            Image(systemName: "paintbrush.fill")
                                .font(.system(size: 16))
                                .foregroundColor(.white)

                            Image(systemName: "textformat")
                                .font(.system(size: 16))
                                .foregroundColor(.white)
                        }
                    }
                    .padding(.horizontal, 16)

                    // Model selector + Duration + Resolution row
                    HStack(spacing: 8) {
                        // Veo 3 selector
                        Text("Veo 3")
                            .font(.custom("Poppins", size: 14).weight(.medium))
                            .foregroundColor(.white)
                            .padding(.horizontal, 12)
                            .padding(.vertical, 4)
                            .background(
                                RoundedRectangle(cornerRadius: 100)
                                    .stroke(Color.white.opacity(0.4), lineWidth: 1)
                            )

                        // Duration: 5s
                        Text("5s")
                            .font(.custom("Poppins", size: 14).weight(.medium))
                            .foregroundColor(.white)
                            .padding(.horizontal, 12)
                            .padding(.vertical, 4)
                            .background(
                                RoundedRectangle(cornerRadius: 100)
                                    .stroke(Color.white.opacity(0.4), lineWidth: 1)
                            )

                        // Resolution: 720P
                        Text("720P")
                            .font(.custom("Poppins", size: 14).weight(.medium))
                            .foregroundColor(.white)
                            .padding(.horizontal, 12)
                            .padding(.vertical, 4)
                            .background(
                                RoundedRectangle(cornerRadius: 100)
                                    .stroke(Color.white.opacity(0.4), lineWidth: 1)
                            )

                        Spacer()
                    }
                    .padding(.horizontal, 16)
                }
                .padding(.bottom, 16)

                // ===== GENERATE BUTTON (RED GRADIENT) =====
                HStack(spacing: 8) {
                    Image(systemName: "flame.fill")
                        .font(.system(size: 18))
                        .foregroundColor(.white)

                    Text("Generate")
                        .font(.custom("Poppins", size: 16).weight(.semibold))
                        .foregroundColor(.white)
                }
                .frame(maxWidth: .infinity)
                .padding(.vertical, 14)
                .background(
                    LinearGradient(
                        colors: [Color(hex: "#ff0000"), Color(hex: "#cc0000")],
                        startPoint: .leading,
                        endPoint: .trailing
                    )
                )
                .cornerRadius(100)
                .padding(.horizontal, 16)
                .padding(.bottom, 16)

                // ===== DISCOVER SECTION =====
                VStack(alignment: .leading, spacing: 12) {
                    Text("Discover")
                        .font(.system(size: 18, weight: .semibold))
                        .foregroundColor(.white)
                        .padding(.horizontal, 16)

                    // 3x2 grid of thumbnails
                    LazyVGrid(columns: [
                        GridItem(.flexible(), spacing: 8),
                        GridItem(.flexible(), spacing: 8),
                        GridItem(.flexible(), spacing: 8)
                    ], spacing: 8) {
                        ForEach(0..<6, id: \.self) { index in
                            ZStack(alignment: .topTrailing) {
                                RoundedRectangle(cornerRadius: 8)
                                    .fill(Color.white.opacity(0.1))
                                    .frame(height: 100)

                                // Model badge overlay
                                if index % 2 == 0 {
                                    Text("Veo 3")
                                        .font(.custom("Inter", size: 9).weight(.medium))
                                        .foregroundColor(.white)
                                        .padding(.horizontal, 6)
                                        .padding(.vertical, 3)
                                        .background(
                                            RoundedRectangle(cornerRadius: 4)
                                                .fill(Color.black.opacity(0.6))
                                        )
                                        .padding(6)
                                } else {
                                    Text("Heygen")
                                        .font(.custom("Inter", size: 9).weight(.medium))
                                        .foregroundColor(.white)
                                        .padding(.horizontal, 6)
                                        .padding(.vertical, 3)
                                        .background(
                                            RoundedRectangle(cornerRadius: 4)
                                                .fill(Color.black.opacity(0.6))
                                        )
                                        .padding(6)
                                }
                            }
                        }
                    }
                    .padding(.horizontal, 16)
                }

                Spacer()
            }
        }
        .frame(width: 390, height: 844)
        .cornerRadius(50)
        .ignoresSafeArea()
    }
}

// MARK: - Color Extension (Hex Support)
extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let a, r, g, b: UInt64
        switch hex.count {
        case 3: // RGB (12-bit)
            (a, r, g, b) = (255, (int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6: // RGB (24-bit)
            (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        case 8: // ARGB (32-bit)
            (a, r, g, b) = (int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (a, r, g, b) = (255, 0, 0, 0)
        }
        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue: Double(b) / 255,
            opacity: Double(a) / 255
        )
    }
}

#Preview {
    TypeSceneText()
}
